// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent that generates trading strategies based on user input.
 *
 * - generateTradingStrategy - A function that generates a trading strategy.
 * - GenerateTradingStrategyInput - The input type for the generateTradingStrategy function.
 * - GenerateTradingStrategyOutput - The return type for the generateTradingStrategy function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTradingStrategyInputSchema = z.object({
  investmentAmount: z.number().describe('The amount of capital to be used for the trading strategy.'),
  riskTolerance: z.enum(['low', 'medium', 'high']).describe('The level of risk the user is willing to take (low, medium, high).'),
  marketConditions: z.string().describe('The current market conditions and trends.'),
  tradingGoals: z.string().describe('The user specified financial goals for this trading strategy.'),
});
export type GenerateTradingStrategyInput = z.infer<typeof GenerateTradingStrategyInputSchema>;

const GenerateTradingStrategyOutputSchema = z.object({
  strategyDescription: z.string().describe('A detailed description of the generated trading strategy.'),
  riskAssessment: z.string().describe('An assessment of the risks associated with the trading strategy.'),
  potentialProfit: z.string().describe('An estimate of the potential profit from the trading strategy based on market conditions.'),
});
export type GenerateTradingStrategyOutput = z.infer<typeof GenerateTradingStrategyOutputSchema>;

export async function generateTradingStrategy(input: GenerateTradingStrategyInput): Promise<GenerateTradingStrategyOutput> {
  return generateTradingStrategyFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTradingStrategyPrompt',
  input: {schema: GenerateTradingStrategyInputSchema},
  output: {schema: GenerateTradingStrategyOutputSchema},
  prompt: `You are an AI-powered trading strategy generator. Given the user's investment amount, risk tolerance, and current market conditions, generate a comprehensive trading strategy.

Investment Amount: {{{investmentAmount}}}
Risk Tolerance: {{{riskTolerance}}}
Market Conditions: {{{marketConditions}}}
Trading Goals: {{{tradingGoals}}}

Consider all these variables when crafting the strategy. Provide a strategy description, assess the risks, and estimate the potential profit.
`,
});

const generateTradingStrategyFlow = ai.defineFlow(
  {
    name: 'generateTradingStrategyFlow',
    inputSchema: GenerateTradingStrategyInputSchema,
    outputSchema: GenerateTradingStrategyOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
